[2024-04-03T09:53:29.815+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_allocate_messages.process_warning_messages manual__2024-04-03T09:53:28.521773+00:00 [queued]>
[2024-04-03T09:53:29.853+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_allocate_messages.process_warning_messages manual__2024-04-03T09:53:28.521773+00:00 [queued]>
[2024-04-03T09:53:29.855+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-04-03T09:53:29.899+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): process_warning_messages> on 2024-04-03 09:53:28.521773+00:00
[2024-04-03T09:53:29.914+0000] {standard_task_runner.py:60} INFO - Started process 14087 to run task
[2024-04-03T09:53:29.928+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_allocate_messages', 'process_warning_messages', 'manual__2024-04-03T09:53:28.521773+00:00', '--job-id', '1284', '--raw', '--subdir', 'DAGS_FOLDER/dag_allocate_messages.py', '--cfg-path', '/tmp/tmp58_ivea9']
[2024-04-03T09:53:29.937+0000] {standard_task_runner.py:88} INFO - Job 1284: Subtask process_warning_messages
[2024-04-03T09:53:30.192+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_allocate_messages.process_warning_messages manual__2024-04-03T09:53:28.521773+00:00 [running]> on host af8488263d95
[2024-04-03T09:53:30.433+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='daniel' AIRFLOW_CTX_DAG_ID='dag_allocate_messages' AIRFLOW_CTX_TASK_ID='process_warning_messages' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T09:53:28.521773+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-03T09:53:28.521773+00:00'
[2024-04-03T09:53:30.438+0000] {logging_mixin.py:188} INFO - proccess warning messages
[2024-04-03T09:53:30.463+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-03T09:53:30.584+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-03T09:53:30.615+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=dag_allocate_messages, task_id=process_warning_messages, execution_date=20240403T095328, start_date=20240403T095329, end_date=20240403T095330
[2024-04-03T09:53:30.682+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-03T09:53:30.754+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
