[2024-04-03T09:32:14.968+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_allocate_messages.process_error_messages manual__2024-04-03T09:32:13.549866+00:00 [queued]>
[2024-04-03T09:32:15.045+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_allocate_messages.process_error_messages manual__2024-04-03T09:32:13.549866+00:00 [queued]>
[2024-04-03T09:32:15.046+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-04-03T09:32:15.124+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): process_error_messages> on 2024-04-03 09:32:13.549866+00:00
[2024-04-03T09:32:15.152+0000] {standard_task_runner.py:60} INFO - Started process 11657 to run task
[2024-04-03T09:32:15.182+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_allocate_messages', 'process_error_messages', 'manual__2024-04-03T09:32:13.549866+00:00', '--job-id', '1249', '--raw', '--subdir', 'DAGS_FOLDER/dag_allocate_messages.py', '--cfg-path', '/tmp/tmp21xb98ha']
[2024-04-03T09:32:15.190+0000] {standard_task_runner.py:88} INFO - Job 1249: Subtask process_error_messages
[2024-04-03T09:32:15.336+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_allocate_messages.process_error_messages manual__2024-04-03T09:32:13.549866+00:00 [running]> on host af8488263d95
[2024-04-03T09:32:15.718+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='daniel' AIRFLOW_CTX_DAG_ID='dag_allocate_messages' AIRFLOW_CTX_TASK_ID='process_error_messages' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T09:32:13.549866+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-03T09:32:13.549866+00:00'
[2024-04-03T09:32:15.723+0000] {logging_mixin.py:188} INFO - proccess error messages
[2024-04-03T09:32:15.758+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-03T09:32:15.809+0000] {logging_mixin.py:188} INFO - insert errr ID: 2
[2024-04-03T09:32:15.812+0000] {logging_mixin.py:188} INFO - insert errr ID: 5
[2024-04-03T09:32:15.883+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-04-03T09:32:15.884+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-04-03T09:32:16.140+0000] {email.py:281} INFO - Sent an alert email to ['daniel.stuckenberger@studmail.htw-aalen.de']
[2024-04-03T09:32:16.268+0000] {logging_mixin.py:188} INFO - proccess error messages
[2024-04-03T09:32:16.286+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-03T09:32:16.299+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=dag_allocate_messages, task_id=process_error_messages, execution_date=20240403T093213, start_date=20240403T093214, end_date=20240403T093216
[2024-04-03T09:32:16.364+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-03T09:32:16.458+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
