[2024-03-27T10:47:23.949+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_allocate_messages.process_error_messages manual__2024-03-27T10:47:19.331979+00:00 [queued]>
[2024-03-27T10:47:23.980+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_allocate_messages.process_error_messages manual__2024-03-27T10:47:19.331979+00:00 [queued]>
[2024-03-27T10:47:23.981+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-03-27T10:47:24.028+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): process_error_messages> on 2024-03-27 10:47:19.331979+00:00
[2024-03-27T10:47:24.045+0000] {standard_task_runner.py:60} INFO - Started process 5793 to run task
[2024-03-27T10:47:24.065+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_allocate_messages', 'process_error_messages', 'manual__2024-03-27T10:47:19.331979+00:00', '--job-id', '1058', '--raw', '--subdir', 'DAGS_FOLDER/dag_allocate_messages.py', '--cfg-path', '/tmp/tmpne2s46gg']
[2024-03-27T10:47:24.073+0000] {standard_task_runner.py:88} INFO - Job 1058: Subtask process_error_messages
[2024-03-27T10:47:24.194+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_allocate_messages.process_error_messages manual__2024-03-27T10:47:19.331979+00:00 [running]> on host 932f824b7ebb
[2024-03-27T10:47:24.405+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='daniel' AIRFLOW_CTX_DAG_ID='dag_allocate_messages' AIRFLOW_CTX_TASK_ID='process_error_messages' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T10:47:19.331979+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-27T10:47:19.331979+00:00'
[2024-03-27T10:47:24.409+0000] {logging_mixin.py:188} INFO - proccess error messages
[2024-03-27T10:47:24.410+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-27T10:47:24.438+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=dag_allocate_messages, task_id=process_error_messages, execution_date=20240327T104719, start_date=20240327T104723, end_date=20240327T104724
[2024-03-27T10:47:24.517+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-27T10:47:24.762+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
