[2024-04-03T09:47:18.990+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_allocate_messages.process_error_messages manual__2024-04-03T09:47:17.348641+00:00 [queued]>
[2024-04-03T09:47:19.013+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_allocate_messages.process_error_messages manual__2024-04-03T09:47:17.348641+00:00 [queued]>
[2024-04-03T09:47:19.014+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-04-03T09:47:19.044+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): process_error_messages> on 2024-04-03 09:47:17.348641+00:00
[2024-04-03T09:47:19.056+0000] {standard_task_runner.py:60} INFO - Started process 13357 to run task
[2024-04-03T09:47:19.067+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_allocate_messages', 'process_error_messages', 'manual__2024-04-03T09:47:17.348641+00:00', '--job-id', '1262', '--raw', '--subdir', 'DAGS_FOLDER/dag_allocate_messages.py', '--cfg-path', '/tmp/tmpebzxipjx']
[2024-04-03T09:47:19.073+0000] {standard_task_runner.py:88} INFO - Job 1262: Subtask process_error_messages
[2024-04-03T09:47:19.197+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_allocate_messages.process_error_messages manual__2024-04-03T09:47:17.348641+00:00 [running]> on host af8488263d95
[2024-04-03T09:47:19.380+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='daniel' AIRFLOW_CTX_DAG_ID='dag_allocate_messages' AIRFLOW_CTX_TASK_ID='process_error_messages' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T09:47:17.348641+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-03T09:47:17.348641+00:00'
[2024-04-03T09:47:19.384+0000] {logging_mixin.py:188} INFO - proccess error messages
[2024-04-03T09:47:19.403+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-03T09:47:19.441+0000] {logging_mixin.py:188} INFO - insert errr ID: 2
[2024-04-03T09:47:19.447+0000] {logging_mixin.py:188} INFO - insert errr ID: 5
[2024-04-03T09:47:19.482+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-04-03T09:47:19.483+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-04-03T09:47:19.712+0000] {email.py:281} INFO - Sent an alert email to ['daniel.stuckenberger@studmail.htw-aalen.de']
[2024-04-03T09:47:19.843+0000] {logging_mixin.py:188} INFO - proccess error messages
[2024-04-03T09:47:19.889+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-03T09:47:19.911+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=dag_allocate_messages, task_id=process_error_messages, execution_date=20240403T094717, start_date=20240403T094718, end_date=20240403T094719
[2024-04-03T09:47:19.971+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-03T09:47:20.016+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
