[2024-04-03T09:53:29.844+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_allocate_messages.process_error_messages manual__2024-04-03T09:53:28.521773+00:00 [queued]>
[2024-04-03T09:53:29.886+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_allocate_messages.process_error_messages manual__2024-04-03T09:53:28.521773+00:00 [queued]>
[2024-04-03T09:53:29.888+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-04-03T09:53:29.944+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): process_error_messages> on 2024-04-03 09:53:28.521773+00:00
[2024-04-03T09:53:29.961+0000] {standard_task_runner.py:60} INFO - Started process 14088 to run task
[2024-04-03T09:53:29.984+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_allocate_messages', 'process_error_messages', 'manual__2024-04-03T09:53:28.521773+00:00', '--job-id', '1285', '--raw', '--subdir', 'DAGS_FOLDER/dag_allocate_messages.py', '--cfg-path', '/tmp/tmprig36bmi']
[2024-04-03T09:53:29.993+0000] {standard_task_runner.py:88} INFO - Job 1285: Subtask process_error_messages
[2024-04-03T09:53:30.255+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_allocate_messages.process_error_messages manual__2024-04-03T09:53:28.521773+00:00 [running]> on host af8488263d95
[2024-04-03T09:53:30.516+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='daniel' AIRFLOW_CTX_DAG_ID='dag_allocate_messages' AIRFLOW_CTX_TASK_ID='process_error_messages' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T09:53:28.521773+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-03T09:53:28.521773+00:00'
[2024-04-03T09:53:30.520+0000] {logging_mixin.py:188} INFO - proccess error messages
[2024-04-03T09:53:30.554+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-04-03T09:53:30.598+0000] {logging_mixin.py:188} INFO - proccess error messages
[2024-04-03T09:53:30.639+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-03T09:53:30.669+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=dag_allocate_messages, task_id=process_error_messages, execution_date=20240403T095328, start_date=20240403T095329, end_date=20240403T095330
[2024-04-03T09:53:30.742+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-03T09:53:30.783+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
